### ISSUE TITLE
How to cleanup (aka remove) secret files after they removed from home-manager config?

### ISSUE THREAD

**Issue by Gerschtli** [jordanisaacs/homeage#6]
The title says it all. There should be a way to remove every via hm deployed secret that is not in the current generation. Otherwise the system could end up in a non reproducible state.

agenix has the same issue as mentioned in my https://github.com/ryantm/agenix/pull/27#issuecomment-963175438.

**Comment by jordanisaacs** [comment]
Currently all secret files are removed through the use of the `secrets` folder. It is a symlink to the home manager build (through the use of `home.file`). Therefore when a home manager upgrade happens, the old age file is not symlinked anymore. This occurs during reboot. It is removed from the file system when you garbage collect your old home manager generations.

However the extra decrypted files will stay until reboot. This could be fixed by adding another layer of linking. So `/secrets-source/` links to `/secrets/` and then unlink the folder on a home manager activation.

**Comment by Gerschtli** [comment]
I think to have a good clean up, all then broken symlinks should be removed too. A solution to this could also solve the cleanup for copied files.

**Comment by jordanisaacs** [comment]
Ya I definitely agree with that. For now broken symlinks are workable (but not ideal) as they at least don't contain the fill. However this introduces the issue where a new file is placed at the same directory with different contents and now the symlink is wrong. A cleanup solution is needed. Would work by adding a `home.activation.homeageCleanup` script after the `writeBoundary`. I created a new issue to track for this. Definitely the highest priority.
